image: "rust:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - target/

stages:
  - build
  - test


build:
  stage: build
  script:
  - cargo update
  - cargo build


test:
  stage: test
  script:
  - cargo test
